- name: Launch an AWS EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:

    # - name: Create a key pair
    #   amazon.aws.ec2_key:
    #     name: sonam_key_pair
    #     region: "us-east-1"
    #     state: present
    #   register: key_pair_info

    # - name: Save the private key locally
    #   copy:
    #     content: "{{ key_pair_info.key.private_key }}"
    #     dest: "./sonam_key_pair.pem"
    #     mode: '0600'  

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "SonamVM"
        key_name: sonam_key_pair
        instance_type: "t2.micro"
        security_group: "default"
        image_id: "ami-08b5b3a93ed654d19"  
        region: "us-east-1"
        count: 1
        network:
          assign_public_ip: true
        wait: yes
      register: ec2_instance

    - name: Display instance details
      debug:
        msg: "EC2 instance {{ ec2_instance.instances[0].public_ip_address }} created successfully"
