services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db ## mongo_data is volume name, /data/db is mounted location

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/todoapp"

volumes:
  mongo_data: 