services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flaskapp
    ports:
      - "3306:3306"
    
  flask-app:
    build: .
    container_name: flask_app
    depends_on:
      - mysql
    ports:
      - "5000:5000"

