apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue ##initially routes using blue one
    ## Just change from blue to green
    ## you will be switching traffic from blue to green environment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
