apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    name: myapp
    version: blue ##initially routes using blue one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
