## green-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: nginx:1.21 # NEW version
        ports:
        - containerPort: 80
