"all":
  "children":
    "backend":
      "hosts":
        "backend1": {}
        "backend2": {}
  "hosts":
    "backend1":
      "ansible_host": "34.239.113.255"
      "ansible_ssh_private_key_file": "todo-app.pem"
      "ansible_user": "ubuntu"
    "backend2":
      "ansible_host": "52.90.222.254"
      "ansible_ssh_private_key_file": "todo-app.pem"
      "ansible_user": "ubuntu"
