# - name: Deploy Backend Application
#   hosts: backend
#   become: yes
#   vars:
#     mongodb_url: "MongoDB connection string here"
#   roles:
#     - backend

- name: Build and deploy frontend app to s3
  hosts: localhost
  vars:
    frontend_path: ../frontend
    s3_bucket: frontend-bucket-for-terraform
  roles:
    - frontend