apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: YWRtaW4= ## Root password admin
  username: bXlzcWwtdXNlcg== ## Base64 of mysql-user
  password: U2VjcmV0UGFzc3dvcmQ= ##Base64 of SecretPassword
